micronaut:
  server:
    port: 8081
  application:
    name: kotlinMicronaut
  router:
    static-resources:
      swagger:
        paths: classpath:static/docs
        mapping: /docs/**
      swagger-ui:
        paths: classpath:static/docs/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3